# Generated by Django 4.1.2 on 2022-10-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0003_alter_announcement_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respond',
            old_name='replyAn',
            new_name='respond_ann',
        ),
        migrations.RenameField(
            model_name='respond',
            old_name='replyUser',
            new_name='respond_user',
        ),
    ]
